version: '3'
services:
  db_server:
    image: postgres
    # volumes:
    #   - ./db_server:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  blog-app:
    build:
      context: blog-app/
      dockerfile: DockerFile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./blog-app:/blog-app
    ports:
      - "8080:3000"
    depends_on:
      - db_server
