version: '3'
services:
  db_server:
    image: postgres
    volumes:
      - ./db_server:/var/lib/postgresql/data
  blog-app:
    build:
      context: blog-app/
      dockerfile: DockerFile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./blog-app:/blog-app
    ports:
      - "3000:3000"
    depends_on:
      - db_server
