default: &default
  adapter: postgresql
  encoding: unicode
  host: db_server
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: blogapp_development

test:
  <<: *default
  database: blogapp_test
