default: &default
  adapter: mysql2
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: 5

development:
  <<: *default
  database: blogapp_development

test:
  <<: *default
  database: blogapp_test
