FROM ruby:2.5.7

RUN apt-get update -qq && apt-get install -y build-essential nodejs default-libmysqlclient-dev npm

RUN mkdir /blog-app
WORKDIR /blog-app
COPY Gemfile /blog-app/Gemfile
COPY Gemfile.lock /blog-app/Gemfile.lock

RUN gem install bundler -v 1.17.3 --no-document && \
  gem install nokogiri -v 1.10.9 --no-document

RUN bundle install
RUN npm install -g yarn
RUN yarn install --check-files

COPY . /blog-app

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
